# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/ebaz4205.xdc

# Block Designs: bd/ebaz4205/ebaz4205.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205 || ORIG_REF_NAME==ebaz4205} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_0_0/ebaz4205_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_0_0 || ORIG_REF_NAME==ebaz4205_xlslice_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_proc_sys_reset_0_0/ebaz4205_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_proc_sys_reset_0_0 || ORIG_REF_NAME==ebaz4205_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_processing_system7_0_0/ebaz4205_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_processing_system7_0_0 || ORIG_REF_NAME==ebaz4205_processing_system7_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_0_0/ebaz4205_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_0_0 || ORIG_REF_NAME==ebaz4205_xlconcat_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xbar_0/ebaz4205_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xbar_0 || ORIG_REF_NAME==ebaz4205_xbar_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_interconnect_0_0/ebaz4205_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_interconnect_0_0 || ORIG_REF_NAME==ebaz4205_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_rst_ENET0_GMII_RX_CLK_0_100M_0/ebaz4205_rst_ENET0_GMII_RX_CLK_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_rst_ENET0_GMII_RX_CLK_0_100M_0 || ORIG_REF_NAME==ebaz4205_rst_ENET0_GMII_RX_CLK_0_100M_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis_capture_0_4/ebaz4205_axis_capture_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis_capture_0_4 || ORIG_REF_NAME==ebaz4205_axis_capture_0_4} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_1_0/ebaz4205_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_1_0 || ORIG_REF_NAME==ebaz4205_xlconcat_1_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_0_0/ebaz4205_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_0_0 || ORIG_REF_NAME==ebaz4205_xlconstant_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_2_0/ebaz4205_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_2_0 || ORIG_REF_NAME==ebaz4205_xlconstant_2_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis_mux_0_0/ebaz4205_axis_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis_mux_0_0 || ORIG_REF_NAME==ebaz4205_axis_mux_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_2_0/ebaz4205_xlconcat_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_2_0 || ORIG_REF_NAME==ebaz4205_xlconcat_2_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_1_0/ebaz4205_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_1_0 || ORIG_REF_NAME==ebaz4205_xlconstant_1_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_3_0/ebaz4205_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_3_0 || ORIG_REF_NAME==ebaz4205_xlconstant_3_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_dds_compiler_0_0/ebaz4205_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_dds_compiler_0_0 || ORIG_REF_NAME==ebaz4205_dds_compiler_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_gpio_1_0/ebaz4205_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_gpio_1_0 || ORIG_REF_NAME==ebaz4205_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_0_1/ebaz4205_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_0_1 || ORIG_REF_NAME==ebaz4205_xlslice_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_3_0/ebaz4205_xlconcat_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_3_0 || ORIG_REF_NAME==ebaz4205_xlconcat_3_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_gpio_0_0/ebaz4205_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_gpio_0_0 || ORIG_REF_NAME==ebaz4205_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_0_1/ebaz4205_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_0_1 || ORIG_REF_NAME==ebaz4205_xlconcat_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_DivideBy2N_0_0/ebaz4205_DivideBy2N_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_DivideBy2N_0_0 || ORIG_REF_NAME==ebaz4205_DivideBy2N_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_dds_compiler_0_1/ebaz4205_dds_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_dds_compiler_0_1 || ORIG_REF_NAME==ebaz4205_dds_compiler_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_I2S_Transmitter_0_1/ebaz4205_I2S_Transmitter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_I2S_Transmitter_0_1 || ORIG_REF_NAME==ebaz4205_I2S_Transmitter_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_mult_gen_0_0/ebaz4205_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_mult_gen_0_0 || ORIG_REF_NAME==ebaz4205_mult_gen_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_0_3/ebaz4205_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_0_3 || ORIG_REF_NAME==ebaz4205_xlslice_0_3} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_RF_test_1MHz_0/ebaz4205_RF_test_1MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_RF_test_1MHz_0 || ORIG_REF_NAME==ebaz4205_RF_test_1MHz_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_gpio_dds_0/ebaz4205_axi_gpio_dds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_gpio_dds_0 || ORIG_REF_NAME==ebaz4205_axi_gpio_dds_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_sin_0/ebaz4205_xlslice_sin_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_sin_0 || ORIG_REF_NAME==ebaz4205_xlslice_sin_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_mult_sin_0/ebaz4205_mult_sin_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_mult_sin_0 || ORIG_REF_NAME==ebaz4205_mult_sin_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_0_4/ebaz4205_xlslice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_0_4 || ORIG_REF_NAME==ebaz4205_xlslice_0_4} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_auto_pc_0/ebaz4205_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_auto_pc_0 || ORIG_REF_NAME==ebaz4205_auto_pc_0} -quiet] -quiet

# XDC: d:/EBAZ4205_SDR/Zynq/capture-test/capture-test.gen/sources_1/bd/ebaz4205/ebaz4205_ooc.xdc
