@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 13 14:22:58 +0100 2022
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim ebaz4205_wrapper_func_synth -key {Post-Synthesis:sim_1:Functional:ebaz4205_wrapper} -tclbatch ebaz4205_wrapper.tcl -protoinst "protoinst_files/ebaz4205.protoinst" -view D:/EBAZ4205_SDR/Zynq/capture-test/ebaz4205_wrapper_behav.wcfg -log simulate.log"
call xsim  ebaz4205_wrapper_func_synth -key {Post-Synthesis:sim_1:Functional:ebaz4205_wrapper} -tclbatch ebaz4205_wrapper.tcl -protoinst "protoinst_files/ebaz4205.protoinst" -view D:/EBAZ4205_SDR/Zynq/capture-test/ebaz4205_wrapper_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
