# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_projects/EBAZ4205_clock_gen_eth_acq/EBAZ4205_clock_gen_eth_acq.srcs/sources_1/bd/ebaz4205/ip/ebaz4205_axi_gpio_0_0/ebaz4205_axi_gpio_0_0.xci
# IP: The module: 'ebaz4205_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_projects/EBAZ4205_clock_gen_eth_acq/EBAZ4205_clock_gen_eth_acq.gen/sources_1/bd/ebaz4205/ip/ebaz4205_axi_gpio_0_0/ebaz4205_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado_projects/EBAZ4205_clock_gen_eth_acq/EBAZ4205_clock_gen_eth_acq.gen/sources_1/bd/ebaz4205/ip/ebaz4205_axi_gpio_0_0/ebaz4205_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado_projects/EBAZ4205_clock_gen_eth_acq/EBAZ4205_clock_gen_eth_acq.gen/sources_1/bd/ebaz4205/ip/ebaz4205_axi_gpio_0_0/ebaz4205_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Vivado_projects/EBAZ4205_clock_gen_eth_acq/EBAZ4205_clock_gen_eth_acq.srcs/sources_1/bd/ebaz4205/ip/ebaz4205_axi_gpio_0_0/ebaz4205_axi_gpio_0_0.xci
# IP: The module: 'ebaz4205_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_projects/EBAZ4205_clock_gen_eth_acq/EBAZ4205_clock_gen_eth_acq.gen/sources_1/bd/ebaz4205/ip/ebaz4205_axi_gpio_0_0/ebaz4205_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado_projects/EBAZ4205_clock_gen_eth_acq/EBAZ4205_clock_gen_eth_acq.gen/sources_1/bd/ebaz4205/ip/ebaz4205_axi_gpio_0_0/ebaz4205_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado_projects/EBAZ4205_clock_gen_eth_acq/EBAZ4205_clock_gen_eth_acq.gen/sources_1/bd/ebaz4205/ip/ebaz4205_axi_gpio_0_0/ebaz4205_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
